config/routes.rb
ChadHydro::Application.routes.draw do
  get "order/index"
  get "redirect/sign_in"
  resources :profiles

  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'about#index'

  get '/about', to: 'about#index'
  get '/blog', to: 'blog#index'
  get '/contact', to: 'contact#index'
  get '/shop', to: 'shop#index'
  get '/shop/category/:category_type', to: 'shop#sort_by_category'
  get '/shop/category/:category_type/:sub_category_type/:sub_category', to: 'shop#sort_by_sub_category', constraints: { :sub_category => /[^\/]+/ }
  get '/shop/product/:product_id', to: 'shop#product'
  get '/shop/product/:product_id/reviews', to: 'shop#product_reviews'
  get '/shop/search', to: 'shop#search_by_title'
  get '/cart', to: 'cart#index'
  get '/blog/new', to: 'blog#new'
  get '/blog/main_article', to: 'blog#main_article'
  get '/blog/update_comments'
  get '/blog/approve'
  get '/blog/edit', to: 'blog#edit'
  get '/admin_settings', to: 'admin#settings'
  get '/newsletter', to: 'admin#newsletter'
  get '/redirect/sign_in', to: 'redirect#sign_in'
  get '/cart/purchase_confirm', to: 'cart#purchase_confirm'
  get '/cart/purchase_error', to: 'cart#purchase_error'
  get '/users/:id/orders', to: 'order#index'
  get '/review/show', to: 'review#show'

  post '/blog/update', to: 'blog#update'
  post '/blog/create', to: 'blog#create'
  post '/send_feedback', to: 'contact#send_feedback'
  post '/add_to_cart/:product_id/:quantity', to: 'cart#add_to_cart'
  post '/remove_from_cart/:product_id/:quantity', to: 'cart#remove_from_cart'
  post '/blog/new_comment', to: 'blog#new_comment'
  post '/blog/process_comments', to: 'blog#process_comments'
  post '/blog/delete_comment', to: 'blog#delete_comment'
  post '/blog/delete_article', to: 'blog#delete_article'
  post '/blog/reset_article_id', to: 'blog#reset_article_id'
  post '/save_settings', to: 'admin#save_settings'
  post '/send_newsletter', to: 'admin#send_newsletter'
  post '/cart/user_check'
  post '/cart/submit_purchase', to: 'cart#submit_purchase'
  post '/admin/change_user_role/:id', to: 'admin#change_user_role'
  post '/review/new', to: 'review#new'
  post '/review/delete', to: 'review#delete'
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :delete_comment, :delete_article, :updte_comments, :approve, :process_comments]
  respond_to :html

  def index
    posts = {}
    @pending_comments = []
    articles = ShopifyAPI::Article.where(blog_id: 6296807).elements
    articles.each do |a|
      date = a.attributes['created_at'].to_datetime.strftime("%B %Y")
      comments = a.comments.elements
      approved_comments = []
      comments.each do |c|
        c.attributes['status'] == 'published' ? (approved_comments << c.attributes) : (@pending_comments << c.attributes)
      end
      a.attributes['comments'] = approved_comments
      posts[date] = [] unless posts.has_key? date
      posts[date] << a.attributes
    end
    @articles = posts.each do |k, v|
      v.sort { |x,y| x['created_at'].to_datetime <=> y['created_at'].to_datetime }
    end
    @articles.each { |k,v| v.reverse!}
  end

  def new
  end

  def reset_article_id
    session[:article_id] = params['id']
    render :nothing => true
  end

  def edit
    @article = ShopifyAPI::Article.find(session[:article_id].to_i)
  end

  def update
    article = ShopifyAPI::Article.find(params['id'])
    article.attributes['body_html'] = params['post_body']
    article.attributes['title'] = params['title']
    article.save
    redirect_to blog_path
  end

  def create
    first_name = current_user.first_name
    last_name = current_user.last_name
    name = "#{first_name} #{last_name}"
    ShopifyAPI::Article.create(blog_id: 6296807, title: params['title'],
                                  body_html: params['post_body'], author: name)
    session[:prev_page] = nil
    redirect_to blog_path
  end

  def new_comment
    comment = {}
    comment['article_id'] = params['article_id']
    comment['author'] = params.has_key?('name') ? params['name'] : 'anonymous'
    comment['body'] = params['comment']
    comment['email'] = params['email']
    response = ShopifyAPI::Comment.create(comment)
    session[:prev_page] = params['article_id']
    if response.errors.messages.any?
        redirect_to blog_path, :error => "Error with comment: #{response.errors.messages.values}"
    elsif admin?
      response.approve
      redirect_to blog_path and return
    else
      redirect_to blog_path, :notice => 'Your comment has been submitted for approval'
    end

  end

  def delete_comment
    response = ShopifyAPI::Comment.find(params['id'].to_i).remove
    status = response ? 200 : 500
    render :nothing => true, :status => status
  end

  def delete_article
    ShopifyAPI::Article.find(params['id'].to_i).destroy
    session[:prev_page] = nil
    render :nothing => true
  end

  def update_comments
    comments = []
    session['article_id'] = params['article_id']
    article_comments = ShopifyAPI::Comment.where(article_id: params['article_id'], status: 'published').elements
    article_comments.each_with_index do |c, i|
      data = c.attributes
      comment = {}
      comment['author'] = data['author']
      comment['created_at'] = data['created_at']
      comment['body'] = data['body']
      comment['id'] = data['id']
      comments << comment
   end
    render partial: '/layouts/comments', :locals => { comments: comments }
  end

  def approve
    @sorted_comments = {}
    @map = {}
    comments = ShopifyAPI::Comment.where(status: 'unapproved')
    comments.each do |c|
      id = c.attributes['article_id']
      @sorted_comments[id] = [] unless @sorted_comments.has_key? id
      @sorted_comments[id] << c.attributes
    end
    @sorted_comments.keys.each do |k|
      title = ShopifyAPI::Article.find(k).attributes['title']
      @map[k] = title
    end
  end

  def process_comments
    params.each do |comment, status|
      approved_count = 0
      removed_count = 0
      case status
      when 'approve'
        ShopifyAPI::Comment.find(comment.to_i).approve
        approved_count += 1
      when 'delete'
        ShopifyAPI::Comment.find(comment.to_i).remove
        removed_count += 1
      else
        next
      end
    end
    redirect_to blog_path, :notice => "Comments successfully updated"
  end

end

app/views/blog/approve.html.haml
%form{role: 'form', method: 'POST', action: '/blog/process_comments'}
  = hidden_field_tag :authenticity_token, form_authenticity_token
  .approval-container
    = link_to "Back", blog_path, class: "font-l"
    %button#update.btn.btn-sm.btn-primary.font-l{type: 'submit'} Save Changes
  .scrollable
    - @sorted_comments.each do |k, v|
      %h3.font-b
        = @map[k]
      - v.each do |comment|
        .comment-box
          .author.font-n
            = "Author: #{comment['author']}"
          .comment-body.font-n
            = "Comment: #{comment['body']}"
          .posted-at.font-n
            - date = comment['created_at'].to_datetime.strftime("%D %I:%M %p")
            = "Posted At: #{date}"
          .approval.radio
            .wait.pull-left
              %input.wait-label.fa-radio.hidden{type: 'radio', id: "wait-#{comment['id']}", name: comment['id'], value: 'wait', 'checked' => 'true'}
              %label{'for' => "wait-#{comment['id']}"}
                = fa_icon 'question 2x', class: "wait-color icon-#{comment['id']}", id: "icon_wait_#{comment['id']}"
            .approve.pull-left
              %input.approve-label.fa-radio.hidden{type: 'radio', id: "approve-#{comment['id']}", name: comment['id'], value: 'approve'}
              %label{'for' => "approve-#{comment['id']}"}
                = fa_icon 'check 2x', class: "icon-faded icon-#{comment['id']}", id: "icon_approve_#{comment['id']}"
            .delete.pull-left
              %input.delete-label.fa-radio.hidden{type: 'radio', id: "delete-#{comment['id']}", name: comment['id'], value: 'delete'}
              %label{'for' => "delete-#{comment['id']}"}
                = fa_icon 'times 2x', class: "icon-faded icon-#{comment['id']}", id: "icon_delete_#{comment['id']}"
          %p.help-block.font-l{id: "help_#{comment['id']}"} * Comment will be ignored
          %hr

app/views/blog/edit.html.haml
= link_to "Back", '/blog', class: 'font-l'
%h2.font-n Edit blog post
.post-container
  %form.form-horizontal{role: 'form', method: 'POST', action: '/blog/update'}
    %input.hidden{name: 'id', value: @article.attributes['id']}
    = hidden_field_tag :authenticity_token, form_authenticity_token
    .form-group
      %label.control-lable.font-n{for: 'postTitle'} Title
      - content = @article.attributes
      %input#postTitle.form-control{name: 'title', value: content['title'], type: 'text', 'required' => 'true'}
    .form-group
      .body-html.hidden{'data-body' => content['body_html']}
      %textarea.tinymce#edit{rows: 10, name: 'post_body', value: content['body_html']}
      = tinymce
    .form-group
      .btn-container
        %button.btn.btn-primary.pull-right.font-l{type: 'submit'} Submit

app/views/blog/index.haml
blog

app/views/blog/index.html.haml
- if session[:prev_page]
  .prev-link.hidden{'data-id' => session[:prev_page]}
- if admin?
  = link_to "New Post", blog_new_path, class: 'font-l'
  - if @pending_comments.any?
    = link_to "Pending comments: #{@pending_comments.count}", blog_approve_path, class: 'pull-right font-l'
.container-fluid
  .main-container.col-md-3
    %h4.font-b Articles
    .article-container
      - first = true
      - @articles.sort_by{|k, v| k.to_datetime}.reverse!.each do |date, post|
        - id = date.gsub(" ", "_")
        - open = first ? 'in' : ''
        - caret = first ? 'fa-caret-down' : 'fa-caret-right'
        .panel-group{id: "accordion_#{id}"}
          .panel.panel-default.articles-panel
            %h4.font-n.blog-panel-title.panel-title
              %a{'data-toggle' => 'collapse', 'data-parent' => "accordion_#{id}", href: "#collapse#{id}"}
                = date
              %i.caret-toggle.fa{class: caret}
          .blog-panel-collapse.panel-collapse.collapse{id: "collapse#{id}", class: open}
            .green.panel-body
              %ul
                - post.each do |a|
                  %li
                    .post
                      - date = a['created_at'].to_datetime.strftime("%D")
                      .data.hidden{'data-article_id' => a['id'], 'data-title' => a['title'], 'data-author' => a['author'], 'data-body' => a['body_html'], 'data-date' => date}
                      %a.font-l.post-title{id: "link_#{a['id']}", href: "#", 'data-id' => a['id']}
                        = a['title']
                - first = false

    - if @articles.any?
      - article = @articles.values.first.first
  .main-article.col-md-5
    = render '/layouts/post', :article => article
  .comments.col-md-2
    .comments-title.pull-left.font-b Comments
    .comment-count.font-b
      = article['comments'].count
    %a.pull-right{href: '#', 'data-toggle' => 'modal', 'data-target' => '#new_comment'}
      = fa_icon "pencil"
      Add Comment
    %hr
    %img.loader.hidden{src: image_path('ajax-loader.gif')}
    .comment-container.scrollable
      = render '/layouts/comments', comments: article['comments']
= render '/layouts/new_comment'

app/views/blog/new.html.haml
= link_to "Back", '/blog', class: 'font-l'
%h2.font-b Create new blog post
.post-container
  %form.form-horizontal{role: 'form', method: 'POST', action: '/blog/create'}
    = hidden_field_tag :authenticity_token, form_authenticity_token
    .form-group
      %label.control-lable.font-n{for: 'postTitle'} Title
      %input#postTitle.form-control{name: 'title', type: 'text', 'required' => 'true'}
    .form-group
      %textarea.tinymce{rows: 10, name: 'post_body'}
      = tinymce
    .form-group
      .btn-container
        %button.btn.btn-primary.pull-right.font-l{type: 'submit'} Submit