config/routes.rb
ChadHydro::Application.routes.draw do
  get "order/index"
  get "redirect/sign_in"
  resources :profiles

  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'about#index'

  get '/about', to: 'about#index'
  get '/blog', to: 'blog#index'
  get '/contact', to: 'contact#index'
  get '/shop', to: 'shop#index'
  get '/shop/category/:category_type', to: 'shop#sort_by_category'
  get '/shop/category/:category_type/:sub_category_type/:sub_category', to: 'shop#sort_by_sub_category', constraints: { :sub_category => /[^\/]+/ }
  get '/shop/product/:product_id', to: 'shop#product'
  get '/shop/product/:product_id/reviews', to: 'shop#product_reviews'
  get '/shop/search', to: 'shop#search_by_title'
  get '/cart', to: 'cart#index'
  get '/blog/new', to: 'blog#new'
  get '/blog/main_article', to: 'blog#main_article'
  get '/blog/update_comments'
  get '/blog/approve'
  get '/blog/edit', to: 'blog#edit'
  get '/admin_settings', to: 'admin#settings'
  get '/newsletter', to: 'admin#newsletter'
  get '/redirect/sign_in', to: 'redirect#sign_in'
  get '/cart/purchase_confirm', to: 'cart#purchase_confirm'
  get '/cart/purchase_error', to: 'cart#purchase_error'
  get '/users/:id/orders', to: 'order#index'
  get '/review/show', to: 'review#show'

  post '/blog/update', to: 'blog#update'
  post '/blog/create', to: 'blog#create'
  post '/send_feedback', to: 'contact#send_feedback'
  post '/add_to_cart/:product_id/:quantity', to: 'cart#add_to_cart'
  post '/remove_from_cart/:product_id/:quantity', to: 'cart#remove_from_cart'
  post '/blog/new_comment', to: 'blog#new_comment'
  post '/blog/process_comments', to: 'blog#process_comments'
  post '/blog/delete_comment', to: 'blog#delete_comment'
  post '/blog/delete_article', to: 'blog#delete_article'
  post '/blog/reset_article_id', to: 'blog#reset_article_id'
  post '/save_settings', to: 'admin#save_settings'
  post '/send_newsletter', to: 'admin#send_newsletter'
  post '/cart/user_check'
  post '/cart/submit_purchase', to: 'cart#submit_purchase'
  post '/admin/change_user_role/:id', to: 'admin#change_user_role'
  post '/review/new', to: 'review#new'
  post '/review/delete', to: 'review#delete'
end

app/views/layouts/_comments.html.haml
- comments.each do |c|
  .comment{id: "comment_#{c['id']}"}
    - if admin?
      .remove-comment.delete-color{'data-id' => c['id']}
        = fa_icon 'times', text: 'Remove Comment'
    .comment-body.font-n
      = c['body']
    .comment-author.article-author.font-l
      = "#{c['author']} - #{c['created_at'].to_datetime.strftime("%D")}"
  %hr{id: "hr_#{c['id']}"}

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-organic{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#nav-items", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a{href: '/'}
        #logo.pull-left
          = image_tag('moonlight-logo.png', {width: '100px;', id: 'logo'})
      #company-name.pull-left
        .nav-header.font-db Moonlight Garden Supply
        #company-phone.font-m
          = phone_number_formatted(Setting.setting_value('general-toll-free-number'))
        #social-media-links.pull-right
          - @social_media_settings.each do |media|
            - unless media.value == 'none'
              = link_to media.value, {target: '_blank'} do
                - media_value = media.name.split('media-').last.split('-').first
                - if media_value == 'facebook'
                  = fa_icon "#{media.name.split('media-').last.split('-').first}-square 2x"
                - else
                  = fa_icon "#{media.name.split('media-').last.split('-').first} 2x"
    .collapse.navbar-collapse#nav-items.custom-nav.navbar-right
      %ul.nav.navbar-nav
        %li
          = link_to("Home", '/about', {class: 'nav_item font-l'})
        %li
          = link_to("Blog", '/blog', {class: 'nav_item font-l'})
        %li
          = link_to("Shop", '/shop', {class: 'nav_item font-l'})
        %li
          = link_to("Contact", '/contact', {class: 'nav_item font-l'})
        %li
          %a{:href => "/cart"}
            = fa_icon "shopping-cart"
            = shopping_cart_count
        %li.dropdown
          %a.settings.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
            %b.fa.fa-gears
          %ul.dropdown-menu
            - if user_signed_in?
              %li.font-db.underline#user_name
                = "Hello #{current_user.first_name}"
              - if admin?
                %li.font-m
                  %a{href: '/admin_settings'} Admin Settings
                %li.font-m
                  %a{href: '/newsletter'} Send Newsletter
              %li.font-m
                = link_to 'Profile', "/profiles/#{current_user.id}"
                = link_to 'Orders', "/users/#{current_user.id}/orders"
                = link_to destroy_user_session_path, {:method => :delete} do
                  Logout
                  = fa_icon "sign-out"
            - else
              %li.font-m
                = link_to 'Sign In', new_user_session_path, :method => :get

app/views/layouts/_new_comment.html.haml
#new_comment.modal.fade{role: 'dialog', 'area-labelledby' => 'newCommentLabel', 'area-hidden' => 'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal'}
          %span &times;
        %h4#newCommentLabel.modal-title.font-b Add New Comment
      #comment_body.modal-body
        %form{role: 'form', method: 'POST', action: '/blog/new_comment'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          %input.comment-article-id.hidden{name: 'article_id'}
          .form-group.has-feedback
            %label.font-n{for: "name"} Name
            %div
              %input#name.form-control{name: 'name', autofocus: "", placeholder: "Enter name", required: "true", type: "text"}/
          .form-group
            .checkbox
              %label
                %input#anon.font-n{type: 'checkbox'} Post anonymously
                %p.help-block.font-l Email is required posting anonymously will hide your name from comments
          .form-group.has-feedback
            %label.font-n{for: "email"}
              Email
            .input-group
            %input#email.form-control{name: 'email', placeholder: "Enter email address", required: "", type: "email"}
          .form-group.has-feedback
            %label.font-n{for: "comments"}
              Comments
            %div
              %textarea#comments.form-control{name: 'comment', placeholder: "Enter comments", required: "", rows: "5", type: "text"}
          .modal-footer
            %button.btn.btn-default.font-l{type: 'button', 'data-dismiss' => 'modal'} Close
            %button.btn.btn-primary.font-l{type: 'submit'} Submit

app/views/layouts/_post.html.haml
- if admin?
  .remove-article.delete-color.pull-left{'data-id' => article['id']}
    = fa_icon 'times', text: 'Remove Article'
  = link_to fa_icon('edit', text: "Edit"), blog_edit_path({:id => article['id']}) , class: 'edit-article approve-color'
.article-header
  %h2.article-title.font-m{'data-id' => article['id'].to_i}
    = article['title']
  %footer
    .article-author.font-l
      - date = article['created_at'].to_datetime.strftime("%D")
      = "#{article['author']} - #{date}"
%blockquote.scrollable
  .article-body.font-n
    = article['body_html'].html_safe

app/views/layouts/_review.html.haml
- @reviews.each do |review|
  .review
    - if admin?
      %a.delete-review{href: '#', 'data-id' => review.id}
        = fa_icon "minus-circle", text: 'Remove'
    .rating{'data-score' => review.rating}
    .review-text
      = review.review_text
  %hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    = analytics_init if Rails.env.production?
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %link{:href => image_path('moonlight-logo.png'), :rel => "shortcut icon", :type => "image/x-icon"}
    %link{:href => image_path('moonlight-logo.png'), :rel => "icon", :type => "image/x-icon"}
    %title Moonlight Garden Supply
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
    = csrf_meta_tags
  %body
    %div#header
      = render :partial => "shared/bflash"
      %header#main_header
        = render :partial => "layouts/header"
    #main-content.container-fluid
      = yield
    %footer#footer.text-center.font-m
      Built With
      = fa_icon "heart"
      By:
      %a{href: 'http://www.cottonwoodcoding.com', target: '_blank'} Cottonwood Coding

app/views/layouts/no_header.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %link{:href => image_path('moonlight-logo.png'), :rel => "shortcut icon", :type => "image/x-icon"}
    %link{:href => image_path('moonlight-logo.png'), :rel => "icon", :type => "image/x-icon"}
    %title Moonlight Garden Supply
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
    = csrf_meta_tags
  %body
    %header
      = render :partial => "shared/bflash"
    .container-fluid
      = yield